version: '3.6'

services: 
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 33066:3306
        environment: 
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'mysqldb'
            MYSQL_USER: 'parker'
            MYSQL_PASSWORD: '1111'
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d

    adminer:
        platform: linux/x86_64
        image: adminer
        restart: always
        links: 
            - mysql
        ports: 
            - 8888:8080